### ISSUE TITLE
 manifest for salesforce/salesforcedx:latest not found

### ISSUE THREAD

**Issue by erlinis** [forcedotcom/salesforcedx-actions#4]
Since a couple of days ago, I am getting this error when using the action to deploy to salesforce

```ruby
Build container for action use: '/home/runner/work/_actions/forcedotcom/salesforcedx-actions/master/Dockerfile'.
  /usr/bin/docker build -t da7a08:95128f6515194e14824f2d8f44c42564 -f
"/home/runner/work/_actions/forcedotcom/salesforcedx-actions/master/Dockerfile" 
"/home/runner/work/_actions/forcedotcom/salesforcedx-actions/master"
  manifest for salesforce/salesforcedx:latest not found: manifest unknown: manifest unknown
```

---
According to this issue in [StackExchange](https://salesforce.stackexchange.com/questions/354209/manifest-for-salesforce-salesforcedxlatest-not-found-manifest-unknown-manifes) with Docker image should be build with `FROM salesforce/salesforcedx:latest-rc-full`

**Comment by rahulmalhotra** [comment]
Thank you @erlinis for sharing the stackexchange link. The fix you mentioned worked really well. I have tested the same in my Salesforce Git Codelab CI: https://github.com/rahulmalhotra/salesforce-git-codelab/runs/3532112257

I have also created a PR to fix this. Although, you can refer to the updated dockerfile here until the PR is merged: https://github.com/rahulmalhotra/salesforcedx-actions/blob/master/Dockerfile

**Comment by mshanemc** [comment]
Hey--just now found this repo.   have updated the docker image
